import { Inter } from "next/font/google";
import "./globals.css";
import "../styles/style.css";
import "../styles/responsive.css";
import "../styles/bootstrap.css";
import "../styles/rtl.css";
// import "../styles/flaticon.css";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";


import Header from "../components/header";
import Footer from "../components/footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Uni Makler",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
